"""Agregar campos de asistencia_confirmada y fecha_asistencia

Revision ID: 89b8e3bb4b19
Revises: 
Create Date: 2025-04-27 14:15:58.902699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b8e3bb4b19'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asistencia_confirmada', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fecha_asistencia', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asistente', schema=None) as batch_op:
        batch_op.drop_column('fecha_asistencia')
        batch_op.drop_column('asistencia_confirmada')

    # ### end Alembic commands ###
